#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Author: Nicolas Paris <nicolas.caen@gmail.com>
# License: GPL

"""
"""
import gettext
gettext.install('tyrs', unicode=1)
import tyrs.tyrs

__revision__ = '0.1'

if __name__=="__main__":
    tyrs.tyrs.main()
