#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Author: Nicolas Paris <nicolas.caen@gmail.com>
# License: GPL

"""
"""
import gettext
gettext.install('tyrs', unicode=1)
from src.tyrs import main

__revision__ = '0.3.2'

if __name__=="__main__":
    main()
