#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Author: Nicolas Paris <nicolas.caen@gmail.com>
# License: GPL

"""
"""
import gettext
gettext.install('tyrs', unicode=1)
from tyrs.tyrs import main
#import cProfile

if __name__=="__main__":
    #cProfile.run('main()')
    main()
