#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Author: Nicolas Paris <nicolas.caen@gmail.com>
# License: GPL

"""
"""
import gettext
gettext.install('tyrs', unicode=1)
from src.tyrs import main
#import cProfile

__revision__ = '0.4.2'

if __name__=="__main__":
    #cProfile.run('main()')
    main()
