#!/usr/bin/env python2
# -*- coding: utf-8 -*-

# Author: Nicolas Paris <nicolas.caen@gmail.com>
# License: GPL

"""
"""
__revision__ = '0.1'

if __name__=="__main__":
    import tyrs.tyrs
    tyrs.tyrs.main()
