#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Author: Nicolas Paris <nicolas.caen@gmail.com>
# License: GPL

"""
"""
import tyrs.tyrs
import gettext

__revision__ = '0.1'

if __name__=="__main__":
    gettext.bindtextdomain('tyrs', '../i18n/fr/')
    gettext.textdomain('tyrs')
    gettext.install('tyrs', unicode=1)
    tyrs.tyrs.main()
